const FaltasPage={
  all:[], funcs:[],
  async init(){
    this.funcs=await App.getAll('funcionarios'); this.all=await App.getAll('faltas');
    App.layout('Faltas','Registro e acompanhamento das ausências dos funcionários',`
      <div class="page-header"><div><h2>Faltas</h2><p>Registre faltas, justificativas e documentos.</p></div><button class="btn btn-primary" id="novaFalta">＋ Registrar falta</button></div>
      <section class="card panel"><div id="faltasTable"></div></section>`);
    document.getElementById('novaFalta').onclick=()=>this.form(); this.render();
  },
  render(){ const fm=Object.fromEntries(this.funcs.map(f=>[f.id,f])); const root=document.getElementById('faltasTable');
    if(!this.all.length){root.innerHTML='<div class="empty"><strong>Nenhuma falta registrada</strong>Clique em “Registrar falta” para adicionar.</div>';return;}
    root.innerHTML=`<div class="table-wrap"><table><thead><tr><th>Funcionário</th><th>Período</th><th>Dias</th><th>Motivo</th><th>Status</th><th>Arquivo</th><th>Ações</th></tr></thead><tbody>${this.all.slice().reverse().map(x=>`<tr><td><strong>${App.escapeHTML(fm[x.funcionarioId]?.nome||'Removido')}</strong></td><td>${App.formatDate(x.dataInicio)} → ${App.formatDate(x.dataFim)}</td><td>${x.quantidadeDias}</td><td>${App.escapeHTML(x.motivo||'—')}</td><td>${App.escapeHTML(x.status)}</td><td>${x.arquivo?`<a href="${x.arquivo}" target="_blank">${App.escapeHTML(x.nomeArquivo||'Abrir')}</a>`:'—'}</td><td><button class="btn btn-secondary btn-sm" onclick="FaltasPage.form('${x.id}')">Editar</button> <button class="btn btn-danger btn-sm" onclick="FaltasPage.del('${x.id}')">Excluir</button></td></tr>`).join('')}</tbody></table></div>`;
  },
  async form(id=null){ const cur=id?await App.get('faltas',id):null;
    App.openModal({title:cur?'Editar falta':'Registrar falta',body:`<form id="faltaForm"><div class="form-grid"><div class="form-group"><label class="form-label">Funcionário *</label><select class="select" name="funcionarioId" required><option value="">Selecione</option>${this.funcs.map(f=>`<option value="${f.id}" ${cur?.funcionarioId===f.id?'selected':''}>${App.escapeHTML(f.nome)}</option>`).join('')}</select></div><div class="form-group"><label class="form-label">Status</label><select class="select" name="status"><option ${cur?.status==='Não justificada'?'selected':''}>Não justificada</option><option ${cur?.status==='Justificada'?'selected':''}>Justificada</option><option ${cur?.status==='Abonada'?'selected':''}>Abonada</option></select></div><div class="form-group"><label class="form-label">Data inicial *</label><input class="input" type="date" name="dataInicio" required value="${cur?.dataInicio||''}"></div><div class="form-group"><label class="form-label">Data final</label><input class="input" type="date" name="dataFim" value="${cur?.dataFim||''}"></div><div class="form-group"><label class="form-label">Quantidade de dias</label><input class="input" type="number" min="1" name="quantidadeDias" value="${cur?.quantidadeDias||1}"></div><div class="form-group"><label class="form-label">Motivo</label><input class="input" name="motivo" value="${App.escapeHTML(cur?.motivo||'')}"></div></div><div class="form-group full" style="margin-top:16px"><label class="form-label">Justificativa</label><textarea class="textarea" name="justificativa">${App.escapeHTML(cur?.justificativa||'')}</textarea></div><div class="form-group full"><label class="form-label">Observações</label><textarea class="textarea" name="observacoes">${App.escapeHTML(cur?.observacoes||'')}</textarea></div><div class="form-group full"><label class="form-label">Anexo (PDF/JPG/PNG)</label><input class="input" id="faltaArquivo" type="file" accept=".pdf,.jpg,.jpeg,.png,application/pdf,image/jpeg,image/png"></div></form>`,footer:`<button class="btn btn-secondary" data-close-modal>Cancelar</button><button class="btn btn-primary" id="salvarFalta">Salvar</button>`});
    document.getElementById('salvarFalta').onclick=async()=>{const form=document.getElementById('faltaForm'); if(!form.reportValidity())return; const fd=new FormData(form); const file=document.getElementById('faltaArquivo').files[0]; let arquivo=cur?.arquivo||null,nomeArquivo=cur?.nomeArquivo||''; try{if(file){const up=await App.uploadFile(file,'faltas'); if(cur?.arquivo)await App.deleteFileByUrl(cur.arquivo); arquivo=up.url; nomeArquivo=up.name;}}catch(e){App.toast('Erro ao enviar o arquivo.','danger');return;} const rec={id:cur?.id||null,funcionarioId:fd.get('funcionarioId'),dataFalta:fd.get('dataInicio'),dataInicio:fd.get('dataInicio'),dataFim:fd.get('dataFim')||fd.get('dataInicio'),quantidadeDias:Number(fd.get('quantidadeDias')||1),motivo:fd.get('motivo'),justificativa:fd.get('justificativa'),observacoes:fd.get('observacoes'),status:fd.get('status'),arquivo,nomeArquivo}; await App.put('faltas',rec); App.closeModal();App.toast('Falta salva com sucesso!');this.all=await App.getAll('faltas');this.render();};
  },
  async del(id){if(!confirm('Excluir esta falta?'))return;const x=await App.get('faltas',id);if(x?.arquivo)await App.deleteFileByUrl(x.arquivo);await App.remove('faltas',id);this.all=await App.getAll('faltas');this.render();App.toast('Falta excluída.');}
};
