const FaltasPage={
  async init(){
    App.layout('Faltas','Controle de faltas dos funcionários',`<div class="page-header"><div><h2>Controle de faltas</h2><p>Registre e consulte as faltas dos funcionários.</p></div><button class="btn btn-primary" id="novaFalta">＋ Registrar falta</button></div><section class="card panel"><div id="faltasTable"></div></section>`);
    document.getElementById('novaFalta').onclick=()=>this.form(); await this.render();
  },
  async render(){const fs=await App.getAll('faltas'); const funcs=await App.getAll('funcionarios'); const map=Object.fromEntries(funcs.map(f=>[f.id,f])); const root=document.getElementById('faltasTable');
    if(!fs.length){root.innerHTML='<div class="empty"><strong>Nenhuma falta registrada</strong>Use o botão “Registrar falta”.</div>';return;}
    root.innerHTML=`<div class="table-wrap"><table><thead><tr><th>Funcionário</th><th>Data</th><th>Tipo</th><th>Justificativa</th><th>Ações</th></tr></thead><tbody>${fs.sort((a,b)=>String(b.data).localeCompare(String(a.data))).map(x=>`<tr><td>${App.escapeHTML(map[x.funcionarioId]?.nome||'—')}</td><td>${App.formatDate(x.data)}</td><td>${App.escapeHTML(x.tipo||'Falta')}</td><td>${App.escapeHTML(x.justificativa||'—')}</td><td><button class="btn btn-danger btn-sm" onclick="FaltasPage.del('${x.id}')">Excluir</button></td></tr>`).join('')}</tbody></table></div>`;
  },
  async form(){const funcs=await App.getAll('funcionarios'); App.openModal({title:'Registrar falta',body:`<form id="faltaForm"><div class="form-group"><label class="form-label">Funcionário</label><select class="select" name="funcionarioId" required><option value="">Selecione</option>${funcs.map(f=>`<option value="${f.id}">${App.escapeHTML(f.nome)}</option>`).join('')}</select></div><div class="form-group"><label class="form-label">Data</label><input class="input" type="date" name="data" required></div><div class="form-group"><label class="form-label">Tipo</label><select class="select" name="tipo"><option>Falta</option><option>Falta justificada</option><option>Atestado</option></select></div><div class="form-group"><label class="form-label">Justificativa</label><textarea class="textarea" name="justificativa"></textarea></div></form>`,footer:'<button class="btn btn-secondary" data-close-modal>Cancelar</button><button class="btn btn-primary" id="salvarFalta">Salvar</button>'}); document.getElementById('salvarFalta').onclick=async()=>{const fd=new FormData(document.getElementById('faltaForm')); if(!fd.get('funcionarioId')||!fd.get('data'))return App.toast('Preencha os campos obrigatórios.','warning'); await App.add('faltas',{funcionarioId:fd.get('funcionarioId'),data:fd.get('data'),tipo:fd.get('tipo'),justificativa:fd.get('justificativa')}); App.closeModal();App.toast('Falta registrada.');this.render();};},
  async del(id){if(confirm('Excluir esta falta?')){await App.remove('faltas',id);App.toast('Falta excluída.');this.render();}}
};