-- SISTEMA DE DECLARAÇÕES - SUPABASE
-- Execute no SQL Editor e clique em Run.

create table if not exists public.declaracoes (
  id bigint generated by default as identity primary key,
  funcionario_id bigint not null references public.funcionarios(id) on delete cascade,
  tipo text not null check (tipo in ('horas','dias')),
  data date not null,
  data_inicial date,
  data_final date,
  hora_inicial time,
  hora_final time,
  quantidade_horas numeric default 0,
  quantidade_dias integer default 0,
  observacoes text,
  arquivo text,
  nome_arquivo text,
  tipo_arquivo text,
  tamanho_arquivo bigint default 0,
  data_cadastro timestamptz default now()
);

create table if not exists public.faltas (
  id bigint generated by default as identity primary key,
  funcionario_id bigint not null references public.funcionarios(id) on delete cascade,
  data date not null,
  tipo text default 'Falta',
  justificativa text,
  observacoes text,
  created_at timestamptz default now()
);

alter table public.funcionarios enable row level security;
alter table public.declaracoes enable row level security;
alter table public.faltas enable row level security;

drop policy if exists "funcionarios acesso" on public.funcionarios;
create policy "funcionarios acesso" on public.funcionarios for all to anon using (true) with check (true);
drop policy if exists "declaracoes acesso" on public.declaracoes;
create policy "declaracoes acesso" on public.declaracoes for all to anon using (true) with check (true);
drop policy if exists "faltas acesso" on public.faltas;
create policy "faltas acesso" on public.faltas for all to anon using (true) with check (true);
