-- EXECUTE ESTE SCRIPT NO SUPABASE: SQL Editor > New query > Run
create table if not exists public.declaracoes (
  id bigint generated by default as identity primary key,
  funcionarioId text not null,
  tipo text not null,
  data date not null,
  dataInicial date,
  dataFinal date,
  horaInicial text,
  horaFinal text,
  quantidadeHoras numeric default 0,
  quantidadeDias integer default 0,
  observacoes text,
  arquivo text,
  nomeArquivo text,
  tipoArquivo text,
  tamanhoArquivo bigint default 0,
  dataCadastro timestamptz default now()
);
create table if not exists public.faltas (
  id bigint generated by default as identity primary key,
  funcionarioId text not null,
  data date not null,
  tipo text default 'Falta',
  justificativa text,
  observacoes text,
  created_at timestamptz default now()
);
alter table public.funcionarios enable row level security;
alter table public.declaracoes enable row level security;
alter table public.faltas enable row level security;
-- ATENÇÃO: políticas abertas permitem que qualquer pessoa com o link leia/altere dados.
-- Use temporariamente até implantarmos login.
drop policy if exists "funcionarios acesso" on public.funcionarios;
create policy "funcionarios acesso" on public.funcionarios for all to anon using (true) with check (true);
drop policy if exists "declaracoes acesso" on public.declaracoes;
create policy "declaracoes acesso" on public.declaracoes for all to anon using (true) with check (true);
drop policy if exists "faltas acesso" on public.faltas;
create policy "faltas acesso" on public.faltas for all to anon using (true) with check (true);
